### ISSUE TITLE
Error in Meta-analysis

### ISSUE THREAD

**Issue by haukethomsen** [soedinglab/b-lore#3]
After the previous error had been resolved, the new version has been downloaded. Unfortunately, the following issue came up in running the meta-analysis:
Calculating summary statistics
Saving results
Reading summary statistics from output/pop1reg
Reading summary statistics from output/pop2reg
Reading summary statistics from output/pop3reg
Combining 3 studies
Locus 1 / 20
Locus 2 / 20
Locus 3 / 20
Locus 4 / 20
Locus 5 / 20
Locus 6 / 20
Locus 7 / 20
Locus 8 / 20
Locus 9 / 20
Locus 10 / 20
Locus 11 / 20
Locus 12 / 20
Locus 13 / 20
Locus 14 / 20
Locus 15 / 20
Locus 16 / 20
Locus 17 / 20
Locus 18 / 20
Locus 19 / 20
Locus 20 / 20
Traceback (most recent call last):
  File "../bin/../blore/main.py", line 289, in <module>
    meta.optimize_hyperparameters(statdir, locusnamesfile, featurefiles, outdir, file_prefix, opts.zmax, opts.muvar, mparams)
  File "/Users/hthomsen/Software/b-lore/blore/meta.py", line 63, in optimize_hyperparameters
    emp_bayes.fit()
  File "/Users/hthomsen/Software/b-lore/blore/inference/empirical_bayes.py", line 96, in fit
    self._callback_zstates(params)
  File "/Users/hthomsen/Software/b-lore/blore/inference/empirical_bayes.py", line 186, in _callback_zstates
    self._global_zstates = [zstatespy.create(self._nsnps[i],
  File "/Users/hthomsen/Software/b-lore/blore/inference/empirical_bayes.py", line 186, in <listcomp>
    self._global_zstates = [zstatespy.create(self._nsnps[i],
  File "/Users/hthomsen/Software/b-lore/blore/inference/zstatespy.py", line 80, in create
    lib = np.ctypeslib.load_library('../lib/zstates.so', _path)
  File "/Users/hthomsen/miniconda3/lib/python3.8/site-packages/numpy/ctypeslib.py", line 163, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension
/Users/hthomsen/Software/b-lore/example$

**Comment by banskt** [comment]
This is an error related to the installation of the package. Did you compile the C libraries using `make` as mentioned in "Installation" section?

**Comment by haukethomsen** [comment]
C libraries were compiled, but the compiler had to be changed in order to meet an incompatible architecture (error was like: have 'arm64', need 'x86_64'). Now, it runs! Thanks for the hint.
